-- Multi-user sessions: per-visitor token rows + PKCE identity handoff.
--
-- Previously the app stored exactly one Spotify session (app_state id = 1),
-- so the last person to connect won and everyone shared it. Now each visitor
-- is identified by an anonymous id (x-app-user) + a server-issued secret
-- (x-app-secret); their tokens live in their own row here.

create table if not exists public.user_tokens (
  user_id text primary key,
  user_secret text not null default '',  -- issued at connect time, fragment-only handoff
  refresh_token text,
  access_token text,
  expires_at bigint,                     -- epoch ms; when the access token expires
  scope text,
  device_id text,                        -- Web Playback SDK device id
  playlist_id text,                      -- per-user default playlist
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The PKCE handshake now also carries the visitor's id + a fresh session
-- secret, generated by /auth/start and read by /auth/callback.
alter table public.pkce_store
  add column if not exists user_id text,
  add column if not exists user_secret text default '';
